name: food
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_swiper_3: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: English
      fonts:
        - asset: assets/fonts/Lora-Bold.ttf
        - asset: assets/fonts/Lora-Italic.ttf
        - asset: assets/fonts/Lora-Regular.ttf
          style: italic
    - family: Burmese
      fonts:
        - asset: assets/fonts/Padauk-Bold.ttf
        - asset: assets/fonts/Padauk-Regular.ttf
          weight: 700
